define({
    "BTN_CANCEL":                   "Cancel", 
    "BTN_CLOSE":                    "Close", 
    "BTN_OK":                       "OK", 
    "BTN_SAVE_DEFAULTS":            "Save Defaults", 
    "BTN_SET_DEFAULTS":             "Set Defaults", 
    "CMD_EXPORT_PDF":               "Export as PDF\u2026",
    "DIALOG_TITLE":                 "Export {0} as PDF",
    "DIALOG_PREFERENCES_TITLE":     "Export as PDF: Set Defaults", 
    "ERROR_PDFKIT_MSG":             "There was an error while creating the PDF document for {0}.",
    "ERROR_PDFKIT_TITLE":           "Unexpected Error",
    "ERROR_UNSUPPORTED_FILE_MSG":   "The following file is not supported and can not be exported as a PDF document: {0}",
    "ERROR_UNSUPPORTED_FILE_TITLE": "Unsupported File",
    "ERROR_WRITE_MSG":              "There was an error while creating your PDF document. Please try again later. If this keeps happening, please open an issue in our Github repository. ({0})",
    "LABEL_FONTSIZE":               "Font Size",
    "LABEL_EXPORT_RANGE":           "Export Range", 
    "LABEL_EXPORT_SELECTION":       "Export Selection",
    "LABEL_EXPORT_CURRENT_FILE":    "Export Current File",
    "LABEL_INCLUDE_PAGES_FOOTER":   "Include Page Numbers in Footer", 
    "LABEL_MARGINS":                "Margins (in printer points)",
    "LABEL_MARGIN_BOTTOM":          "Bottom Margin", 
    "LABEL_MARGIN_LEFT":            "Left Margin", 
    "LABEL_MARGIN_RIGHT":           "Right Margin", 
    "LABEL_MARGIN_TOP":             "Top Margin", 
    "LABEL_OPENPDF":                "Open PDF After Export", 
    "LABEL_SELECTION":              "Selection", 
    "LABEL_WHOLEFILE":              "Whole File" 
});
