define({
    "BTN_CANCEL":                   "Cancella", 
    "BTN_CLOSE":                    "Chiudi", 
    "BTN_OK":                       "OK", 
    "BTN_SAVE_DEFAULTS":            "Salva Default", 
    "BTN_SET_DEFAULTS":             "Imposta Default", 
    "CMD_EXPORT_PDF":               "Esporta come PDF\u2026",
    "DIALOG_TITLE":                 "Esporta {0} come PDF",
    "DIALOG_PREFERENCES_TITLE":     "Esporta come PDF: Impostazioni di Default", 
    "ERROR_PDFKIT_MSG":             "c'é un errore durante la creazione del documento PDF per {0}.",
    "ERROR_PDFKIT_TITLE":           "Errore inatteso",
    "ERROR_UNSUPPORTED_FILE_MSG":   "Il seguente file non è supportata e non può essere esportato come documento PDF: {0}",
    "ERROR_UNSUPPORTED_FILE_TITLE": "File non supportato",
    "ERROR_WRITE_MSG":              "Si è verificato un errore durante la creazione del documento PDF. Per favore riprova più tardi. Se questo continua a succedere, si prega di aprire un problema nel nostro repository GitHub. ({0})",
    "LABEL_FONTSIZE":               "Dimensioni carattere",
    "LABEL_EXPORT_RANGE":           "Esporta intervallo", 
    "LABEL_EXPORT_SELECTION":       "Esporta selezione",
    "LABEL_EXPORT_CURRENT_FILE":    "Esporta file corrente",
    "LABEL_MARGINS":                "Margini (in punto di stampa)",
    "LABEL_MARGIN_BOTTOM":          "Margine inferiore", 
    "LABEL_MARGIN_LEFT":            "Margnine sinistro", 
    "LABEL_MARGIN_RIGHT":           "Margine destro", 
    "LABEL_MARGIN_TOP":             "Margine alto", 
    "LABEL_OPENPDF":                "Apri il PDF dopo l'esportazione", 
    "LABEL_SELECTION":              "Seleziona", 
    "LABEL_WHOLEFILE":              "Tutto File" 
});
